import image1 from "../assets/img/image-1.png";
import image2 from "../assets/img/image-2.png";
import image3 from "../assets/img/image-3.png";
import image4 from "../assets/img/image-4.png";
import { ReactComponent as Icicles } from "../assets/img/icicles.svg";
import { ReactComponent as Gem } from "../assets/img/gem.svg";
import { ReactComponent as FireFlameCurved } from "../assets/img/fire-flame-curved.svg";

const artworks = [
  {
    id: 1,
    image: image1,
    title: "Astropups #1283",
    royalty: "5%",
    currentFloor: "15N",
    rarity: <Icicles />,
    history: [
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        to: "pixel8llc.near",
        type: "Transfer",
        explorer_link: "",
        status: "Succeeded",
      },
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        type: "Transfer",
        explorer_link: "",
        status: "Failed",
      },
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        type: "Mint",
        explorer_link: "",
        status: "Pending",
      },
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        to: "pixel8llc.near",
        type: "Transfer",
        explorer_link: "",
        status: "Succeeded",
      },
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        to: "pixel8llc.near",
        type: "Transfer",
        explorer_link: "",
        status: "Failed",
      },
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        to: "pixel8llc.near",
        no_of_mints: 2,
        type: "Mint",
        explorer_link: "",
        status: "Pending",
      },
    ],
  },
  {
    id: 2,
    image: image2,
    title: "Vexed Apes Club #52",
    royalty: "5%",
    currentFloor: "15N",
    rarity: <Gem />,
    history: [
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        to: "pixel8llc.near",
        type: "Transfer",
        explorer_link: "",
        status: "Succeeded",
      },
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        type: "Transfer",
        explorer_link: "",
        status: "Failed",
      },
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        type: "Mint",
        explorer_link: "",
        status: "Pending",
      },
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        to: "pixel8llc.near",
        type: "Transfer",
        explorer_link: "",
        status: "Succeeded",
      },
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        to: "pixel8llc.near",
        type: "Transfer",
        explorer_link: "",
        status: "Failed",
      },
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        to: "pixel8llc.near",
        no_of_mints: 2,
        type: "Mint",
        explorer_link: "",
        status: "Pending",
      },
    ],
  },
  {
    id: 3,
    image: image3,
    title: "VexedApesClub#898",
    royalty: "5%",
    currentFloor: "15N",
    rarity: <FireFlameCurved />,
    history: [
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        to: "pixel8llc.near",
        type: "Transfer",
        explorer_link: "",
        status: "Succeeded",
      },
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        type: "Transfer",
        explorer_link: "",
        status: "Failed",
      },
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        type: "Mint",
        explorer_link: "",
        status: "Pending",
      },
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        to: "pixel8llc.near",
        type: "Transfer",
        explorer_link: "",
        status: "Succeeded",
      },
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        to: "pixel8llc.near",
        type: "Transfer",
        explorer_link: "",
        status: "Failed",
      },
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        to: "pixel8llc.near",
        no_of_mints: 2,
        type: "Mint",
        explorer_link: "",
        status: "Pending",
      },
    ],
  },
  {
    id: 4,
    image: image4,
    title: "Blue Bob Boom! Promotional DAC - Design 3 #176",
    royalty: "5%",
    currentFloor: "15N",
    rarity: <FireFlameCurved />,
    history: [
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        to: "pixel8llc.near",
        type: "Transfer",
        explorer_link: "",
        status: "Succeeded",
      },
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        type: "Transfer",
        explorer_link: "",
        status: "Failed",
      },
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        type: "Mint",
        explorer_link: "",
        status: "Pending",
      },
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        to: "pixel8llc.near",
        type: "Transfer",
        explorer_link: "",
        status: "Succeeded",
      },
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        to: "pixel8llc.near",
        type: "Transfer",
        explorer_link: "",
        status: "Failed",
      },
      {
        date: "2/27/22",
        from: "pixel8llc.near",
        to: "pixel8llc.near",
        no_of_mints: 2,
        type: "Mint",
        explorer_link: "",
        status: "Pending",
      },
    ],
  },
];

export default artworks;
